all:
  layout: %SF_ROOT_DIR%/plugins/sfPlopPlugin/modules/sfPlopCMS/templates/layout_plugin
  javascripts:
    - /sfPlopPlugin/js/all.min.js
  stylesheets:
    - /sfPlopPlugin/css/all.min.css
    - /sfPlopPlugin/vendor/jquery/css/black-tie/jquery-ui-1.8.17.css